Update github actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,7 @@ name: Test, transfer and run
 on: [push, pull_request]
 
 jobs:
-  build:
+  test-build-transfer-run:
     runs-on: ubuntu-latest
 
     steps:
@@ -67,8 +67,29 @@ jobs:
         sshpass -p "$SCP_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./matrixB.txt $SCP_USERNAME@login.g100.cineca.it:/g100/home/usertrain/$SCP_USERNAME/
         sshpass -p "$SCP_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./myimage.sif $SCP_USERNAME@login.g100.cineca.it:/g100/home/usertrain/$SCP_USERNAME/
 
-    - name: Run the job on the cluster
+    - name: Run on the cluster
       env:
         SSH_USERNAME: ${{ secrets.SCP_USERNAME }}
         SSH_PASSWORD: ${{ secrets.SCP_PASSWORD }}
-      run: sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$SSH_USERNAME@login.g100.cineca.it" 'bash -s' < ./job.sh
+      run: sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$SSH_USERNAME@login.g100.cineca.it" 'rm output.txt && rm error.txt && bash ./job.sh'
+      
+    - name: Transfer the outputs back from the cluster
+      env:
+        SCP_USERNAME: ${{ secrets.SCP_USERNAME }}
+        SCP_PASSWORD: ${{ secrets.SCP_PASSWORD }}
+      run: |
+        sshpass -p "$SCP_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r $SCP_USERNAME@login.g100.cineca.it:/g100/home/usertrain/$SCP_USERNAME/output.txt output_cluster.txt
+        sshpass -p "$SCP_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r $SCP_USERNAME@login.g100.cineca.it:/g100/home/usertrain/$SCP_USERNAME/error.txt error_cluster.txt
+    
+    - name: Check the execution outputs
+      run: |
+      	if ! cmp -s error.txt error_cluster.txt; then
+	      echo "Output files are different!"
+	      exit 1
+	    fi
+	    if ! cmp -s output.txt output_cluster.txt; then
+	      echo "Error files are different!"
+	      exit 1
+	    else
+	      echo "Output and error files match with the expected ones"
+	    fi
